### ISSUE TITLE
Both illuminate/html and laravelcollective/html is installed

### ISSUE THREAD

**Issue by amenk** [vi-kon/laravel-wiki#1]
```
 - Installing laravelcollective/html (5.2.x-dev add2c74)
   Cloning add2c74b144d0a25ba27a1506b7ce84e6bcadd64

 - Installing illuminate/html (dev-master 3d1009b)
   Cloning 3d1009bb8e0f25720c914af5c1f4015dd373c9ef
```

Could that cause problems?

**Comment by vincekovacs** [comment]
Both packages registers their services in container with same name, so this may cause problem.

By the way the `illuminate/html` package is abandoned and no longer maintained. The authors suggests using the `laravelcollective/html` package instead.

**Comment by amenk** [comment]
I Know. the illuminate one seems to be used in some of your own deps. so you have to change there.

**Comment by vincekovacs** [comment]
Oh :) Thank you, I found that `vi-kon/laravel-parser-markdown` uses `illuminate/html`, but not uses any method from it.
